-- Emote directory.
TwitchEmotes_defaultpack["danW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\danW.tga:28:28"
TwitchEmotes_defaultpack["darniasCoke"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\darniasCoke.tga:28:28"
TwitchEmotes_defaultpack["getMad"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\getMad.tga:28:28"
TwitchEmotes_defaultpack["gQt"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\gQt.tga:28:28"
TwitchEmotes_defaultpack["kalliW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kalliW.tga:28:28"
TwitchEmotes_defaultpack["kaztoS"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kaztoS.tga:28:28"
TwitchEmotes_defaultpack["kingCool"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kingCool.tga:28:28"
TwitchEmotes_defaultpack["kingCoolHD"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kingCoolHD.tga:28:28"
TwitchEmotes_defaultpack["kingLUL"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kingLUL.tga:28:28"
TwitchEmotes_defaultpack["kingP"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kingP.tga:28:28"
TwitchEmotes_defaultpack["kingSad"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kingSad.tga:28:28"
TwitchEmotes_defaultpack["kingW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kingW.tga:28:28"
TwitchEmotes_defaultpack["markusW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\markusW.tga:28:28"
TwitchEmotes_defaultpack["nostamPray"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\nostamPray.tga:28:28"
TwitchEmotes_defaultpack["Pakka"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Pakka.tga:28:28"
TwitchEmotes_defaultpack["resttC"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\resttC.tga:28:28"
TwitchEmotes_defaultpack["RollSafe"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\RollSafe.tga:28:28"
TwitchEmotes_defaultpack["rumbleW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\rumbleW.tga:28:28"
TwitchEmotes_defaultpack["thinkW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\thinkW.tga:28:28"
TwitchEmotes_defaultpack["wChair"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\wChair.tga:28:28"
TwitchEmotes_defaultpack["yungW"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\yungW.tga:28:28"
TwitchEmotes_defaultpack["kingChain"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\kingChain.tga:28:28"
TwitchEmotes_defaultpack["KEKBye"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\KEKBye.tga:28:28"
TwitchEmotes_defaultpack["HOPIUM"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\HOPIUM.tga:28:28"
TwitchEmotes_defaultpack["pepeGUN"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\pepeGUN.tga:28:28"
TwitchEmotes_defaultpack["BASED"] = "Interface\\AddOns\\TwitchEmotes\\Archetype\\BASED.tga:28:28"
TwitchEmotes_defaultpack["donoWall"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\donoWall.tga:28:28"
TwitchEmotes_defaultpack["CHAD"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\CHAD.tga:28:28"
TwitchEmotes_defaultpack["peepoHey"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoHey.tga:28:28"
TwitchEmotes_defaultpack["peepoBye"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoBye.tga:28:28"
TwitchEmotes_defaultpack["ricardoFlick"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\ricardoFlick.tga:28:28"
TwitchEmotes_defaultpack["Hmm"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Hmm.tga:28:28"
TwitchEmotes_defaultpack["relaxBRO"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\relaxBRO.tga:28:28"
TwitchEmotes_defaultpack["Weirdge"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Weirdge.tga:28:28"
TwitchEmotes_defaultpack["Glaivege"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Glaivege.tga:28:28"
TwitchEmotes_defaultpack["glaiveS"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\glaiveS.tga:28:28"
TwitchEmotes_defaultpack["PARSEQVIST"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Parseqvist.tga:28:28"
TwitchEmotes_defaultpack["ICANT"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\ICANT.tga:28:28"
TwitchEmotes_defaultpack["Thiefege"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Thiefege.tga:28:28"
TwitchEmotes_defaultpack["NOPE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\NOPE.tga:28:28"
TwitchEmotes_defaultpack["MINE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\MINE.tga:28:28"
TwitchEmotes_defaultpack["HUH"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\HUH.tga:28:28"
TwitchEmotes_defaultpack["Miranki"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Miranki.tga:28:28"
TwitchEmotes_defaultpack["ICANTT"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\ICANTT.tga:28:28"
TwitchEmotes_defaultpack["DAB"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\DAB.tga:28:28"
TwitchEmotes_defaultpack["HEYE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\HEYE.tga:28:28"
TwitchEmotes_defaultpack["OK"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\OK.tga:28:28"

TwitchEmotes_defaultpack["PepeBusiness"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeBusiness.tga:28:28"
TwitchEmotes_defaultpack["WICKEDLEAVE"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\WICKEDLEAVE.tga:28:28"
TwitchEmotes_defaultpack["peepoEnter"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoEnter.tga:32:32"
TwitchEmotes_defaultpack["PepeLootBan"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeLootBan.tga:32:64"
TwitchEmotes_defaultpack["PepeRuns"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeRuns.tga:28:28"
TwitchEmotes_defaultpack["PepeHowdy"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeHowdy.tga:28:28"
TwitchEmotes_defaultpack["MontyJAM"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\MontyJAM.tga:28:28"
TwitchEmotes_defaultpack["peepoBath"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoBath.tga:36:36"
TwitchEmotes_defaultpack["peepoPog"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoPog.tga:32:32"
TwitchEmotes_defaultpack["peepoCouchLurk"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoCouchLurk.tga:36:36"
TwitchEmotes_defaultpack["peepoStream"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoStream.tga:36:36"
TwitchEmotes_defaultpack["peepoSweg"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\peepoSweg.tga:36:36"
TwitchEmotes_defaultpack["PepeGreenCard"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeGreenCard.tga:32:32"
TwitchEmotes_defaultpack["PepeYellowCard"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeYellowCard.tga:32:32"
TwitchEmotes_defaultpack["PepeRedCard"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeRedCard.tga:32:32"
TwitchEmotes_defaultpack["SadCatThumbsUp"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\SadCatThumbsUp.tga:32:32"
TwitchEmotes_defaultpack["MadCat"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\MadCat.tga:28:28"
TwitchEmotes_defaultpack["WhatIsLove"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\WhatIsLove.tga:32:32"
TwitchEmotes_defaultpack["dbMad"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\dbMad.tga:28:28"
TwitchEmotes_defaultpack["dbShook"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\dbShook.tga:28:56"
TwitchEmotes_defaultpack["Chickenge"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\Chickenge.tga:28:28"
TwitchEmotes_defaultpack["PepeBait"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeBait.tga:28:28"
TwitchEmotes_defaultpack["MontyDeal"] = "Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\MontyDeal.tga:28:28"

-- Emote animation data.
TwitchEmotes_animation_metadata["Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeRuns.tga"] = {["nFrames"] = 6, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 256, ["framerate"] = 16}
TwitchEmotes_animation_metadata["Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\PepeHowdy.tga"] = {["nFrames"] = 12, ["frameWidth"] = 32, ["frameHeight"] = 32, ["imageWidth"] = 32, ["imageHeight"] = 512, ["framerate"] = 12}
TwitchEmotes_animation_metadata["Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\MontyJAM.tga"] = {["nFrames"] = 13, ["frameWidth"] = 64, ["frameHeight"] = 64, ["imageWidth"] = 64, ["imageHeight"] = 1024, ["framerate"] = 13}
TwitchEmotes_animation_metadata["Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\WhatIsLove.tga"] = {["nFrames"] = 6, ["frameWidth"] = 64, ["frameHeight"] = 64, ["imageWidth"] = 64, ["imageHeight"] = 512, ["framerate"] = 12}
TwitchEmotes_animation_metadata["Interface\\AddOns\\TwitchEmotes\\Emotes\\Archetype\\MontyDeal.tga"] = {["nFrames"] = 8, ["frameWidth"] = 64, ["frameHeight"] = 64, ["imageWidth"] = 64, ["imageHeight"] = 512, ["framerate"] = 8}

-- Emote name references.
TwitchEmotes_emoticons["danW"] = "danW"
TwitchEmotes_emoticons["darniasCoke"] = "darniasCoke"
TwitchEmotes_emoticons["getMad"] = "getMad"
TwitchEmotes_emoticons["kalliW"] = "kalliW"
TwitchEmotes_emoticons["kaztoS"] = "kaztoS"
TwitchEmotes_emoticons["kingCool"] = "kingCool"
TwitchEmotes_emoticons["kingCoolHD"] = "kingCoolHD"
TwitchEmotes_emoticons["kingLUL"] = "kingLUL"
TwitchEmotes_emoticons["kingP"] = "kingP"
TwitchEmotes_emoticons["kingSad"] = "kingSad"
TwitchEmotes_emoticons["kingW"] = "kingW"
TwitchEmotes_emoticons["markusW"] = "markusW"
TwitchEmotes_emoticons["nostamPray"] = "nostamPray"
TwitchEmotes_emoticons["Pakka"] = "Pakka"
TwitchEmotes_emoticons["resttC"] = "resttC"
TwitchEmotes_emoticons["RollSafe"] = "RollSafe"
TwitchEmotes_emoticons["rumbleW"] = "rumbleW"
TwitchEmotes_emoticons["thinkW"] = "thinkW"
TwitchEmotes_emoticons["wChair"] = "wChair"
TwitchEmotes_emoticons["yungW"] = "yungW"
TwitchEmotes_emoticons["kingChain"] = "kingChain"
TwitchEmotes_emoticons["KEKBye"] = "KEKBye"
TwitchEmotes_emoticons["HOPIUM"] = "HOPIUM"
TwitchEmotes_emoticons["pepeGUN"] = "pepeGUN"
TwitchEmotes_emoticons["BASED"] = "BASED"
TwitchEmotes_emoticons["donoWall"] = "donoWall"
TwitchEmotes_emoticons["CHAD"] = "CHAD"
TwitchEmotes_emoticons["peepoHey"] = "peepoHey"
TwitchEmotes_emoticons["peepoBye"] = "peepoBye"
TwitchEmotes_emoticons["ricardoFlick"] = "ricardoFlick"
TwitchEmotes_emoticons["Hmm"] = "Hmm"
TwitchEmotes_emoticons["relaxBRO"] = "relaxBRO"
TwitchEmotes_emoticons["Weirdge"] = "Weirdge"
TwitchEmotes_emoticons["Glaivege"] = "Glaivege"
TwitchEmotes_emoticons["PARSEQVIST"] = "PARSEQVIST"
TwitchEmotes_emoticons["ICANT"] = "ICANT"
TwitchEmotes_emoticons["Thiefege"] = "Thiefege"
TwitchEmotes_emoticons["NOPE"] = "NOPE"
TwitchEmotes_emoticons["MINE"] = "MINE"
TwitchEmotes_emoticons["HUH"] = "HUH"
TwitchEmotes_emoticons["Miranki"] = "Miranki"
TwitchEmotes_emoticons["ICANTT"] = "ICANTT"
TwitchEmotes_emoticons["DAB"] = "DAB"
TwitchEmotes_emoticons["HEYE"] = "HEYE"
TwitchEmotes_emoticons["OK"] = "OK"

TwitchEmotes_emoticons["PepeBusiness"] = "PepeBusiness"
TwitchEmotes_emoticons["WICKEDLEAVE"] = "WICKEDLEAVE"
TwitchEmotes_emoticons["peepoEnter"] = "peepoEnter"
TwitchEmotes_emoticons["PepeLootBan"] = "PepeLootBan"
TwitchEmotes_emoticons["PepeRuns"] = "PepeRuns"
TwitchEmotes_emoticons["PepeHowdy"] = "PepeHowdy"
TwitchEmotes_emoticons["MontyJAM"] = "MontyJAM"
TwitchEmotes_emoticons["peepoBath"] = "peepoBath"
TwitchEmotes_emoticons["peepoPog"] = "peepoPog"
TwitchEmotes_emoticons["peepoCouchLurk"] = "peepoCouchLurk"
TwitchEmotes_emoticons["peepoStream"] = "peepoStream"
TwitchEmotes_emoticons["peepoSweg"] = "peepoSweg"
TwitchEmotes_emoticons["PepeGreenCard"] = "PepeGreenCard"
TwitchEmotes_emoticons["PepeYellowCard"] = "PepeYellowCard"
TwitchEmotes_emoticons["PepeRedCard"] = "PepeRedCard"
TwitchEmotes_emoticons["SadCatThumbsUp"] = "SadCatThumbsUp"
TwitchEmotes_emoticons["MadCat"] = "MadCat"
TwitchEmotes_emoticons["WhatIsLove"] = "WhatIsLove"
TwitchEmotes_emoticons["dbMad"] = "dbMad"
TwitchEmotes_emoticons["dbShook"] = "dbShook"
TwitchEmotes_emoticons["Chickenge"] = "Chickenge"
TwitchEmotes_emoticons["PepeBait"] = "PepeBait"
TwitchEmotes_emoticons["MontyDeal"] = "MontyDeal"

-- Emote category - MAX 45 EMOTES PER CATEGORY.
TwitchEmotes_dropdown_options[#TwitchEmotes_dropdown_options + 1] = {  "Archetype 1", 
	"danW", "darniasCoke", "getMad", "gQt", "kalliW", "kaztoS", 
    "kingCool", "kingCoolHD", "kingLUL", "kingP", "kingSad", "kingW", "markusW", 
    "nostamPray", "Pakka", "resttC", "RollSafe", "rumbleW", "thinkW", "wChair", "yungW",
    "relaxBRO", "Weirdge", "Glaivege", "ICANT", "ICANTT", "Thiefege", "NOPE", "MINE", 
    "HUH", "DAB", "HEYE", "OK", "PARSEQVIST"
}

TwitchEmotes_dropdown_options[#TwitchEmotes_dropdown_options + 1] = { "Archetype 2", 
	"PepeBusiness", "WICKEDLEAVE", "peepoEnter", "PepeLootBan", "peepoBath",
	"peepoPog", "peepoCouchLurk", "peepoStream", "peepoSweg", "PepeGreenCard",
	"PepeYellowCard", "PepeRedCard", "SadCatThumbsUp", "MadCat", "dbMad", "dbShook",
	"Chickenge", "PepeBait"
}

TwitchEmotes_dropdown_options[#TwitchEmotes_dropdown_options + 1] = { "Archetype GIFs", 
	"PepeRuns", "PepeHowdy", "MontyJAM", "WhatIsLove", "MontyDeal"
}